name: Hola Mundo

on: [push]

jobs:
  uno:
    runs-on: ubuntu-latest

    steps:
      - name: Prueba Actions
        uses: ./.github/actions/my-action
  dos: 
    runs-on: ubuntu-latest
     
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.2.1
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
        with: 
          node-version: latest
      - name: Version de Node
        run: node --version
#Instalar dependecias
      - name: Instalar dependencias
        run: npm install 

  tres:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.31.1
        with:
          php-version: '8.3'
      



