name: Hola Mundo

on: [push]

jobs:
  uno:
    runs-on: ubuntu-latest

    steps:
      - name: Mensaje
        run: echo "Hola Mundo" 
      - name: Touch File   #Crea
        run: | 
             touch hola.txt
             ls -al
      - name: Set text    #Agrega
        run: |
             echo "Hola mundo" >> hola.txt
             ls -al
      - name: Read File  #Lee
        run: | 
          cat hola.txt
          ls -al
  dos: 
    runs-on: ubuntu-latest
     
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.2.1
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4

      - name: Version de Node
          run: node --version






